Update panel serve commandline argument docs
holoviz/panel pull request #1976
Opened 2021-02-12 10:48 UTC by philippjfr

2021-02-12 12:04 UTC, khannaum requested changes

2021-02-12 12:04 UTC, khannaum commented on examples/user_guide/Deploy_and_Export.ipynb
> +    "      --session-token-expiration N\n",
it is in milliseconds

2021-02-12 18:45 UTC, philippjfr commented on examples/user_guide/Deploy_and_Export.ipynb
> +    "      --session-token-expiration N\n",
It's not though, it checks against:

```
now = calendar.timegm(dt.datetime.utcnow().utctimetuple())
```

2021-02-12 18:45 UTC, merged

2021-02-14 04:49 UTC, khannaum commented on examples/user_guide/Deploy_and_Export.ipynb
> +    "      --session-token-expiration N\n",
Ok