Fixed broken link in gh-actions badge
holoviz/panel pull request #2325
Opened 2021-05-17 16:04 UTC by jlstevens

Not sure what the intended link was but it isn't working so I'm proposing what I think was supposed to be the target...

2021-05-17 16:05 UTC, jlstevens commented
Hvplot uses: `https://github.com/holoviz/hvplot/actions?query=workflow%3Atests`

2021-05-17 16:14 UTC, philippjfr commented
Thanks, I think they actually changed the URL at some point.

2021-05-17 16:19 UTC, Hoxbro commented
Would it not be better to have it referencing the master branch? This can be done by appending`?query=branch%3Amaster` to both urls.

2021-05-17 16:23 UTC, philippjfr commented
Good suggestion @Hoxbro. If you have the time @jlstevens we should do that everywhere.

2021-05-17 17:04 UTC, jlstevens commented
> ... we should do that everywhere.

I'm happy to update our main projects (and list the ones that I updated) but I'm not sure about *everywhere* as such. :-)

2021-05-18 03:02 UTC, jbednar approved these changes

2021-05-18 10:16 UTC, philippjfr requested changes
Will merge once this links to the master branch as Hoxbro suggested.

2021-05-18 10:17 UTC, philippjfr commented on README.md
> +| Build Status | [![Linux/MacOS Build Status](https://github.com/holoviz/panel/workflows/pytest/badge.svg)](https://github.com/holoviz/panel/actions/workflows/test.yaml)
```suggestion
| Build Status | [![Linux/MacOS Build Status](https://github.com/holoviz/panel/workflows/pytest/badge.svg?query=branch%3Amaster)](https://github.com/holoviz/panel/actions/workflows/test.yaml?query=branch%3Amaster)
```

2021-05-18 10:18 UTC, philippjfr approved these changes

2021-05-18 10:43 UTC, merged