Add chat area input and integrate
holoviz/panel pull request #6379
Opened 2024-02-23 06:40 UTC by ahuang11

Closes https://github.com/holoviz/panel/issues/6284
Upon clicking shift enter, triggers `value`. (Actually I should probably remove the shift to be consistent with ChatGPT).

Something seems fishy about handling both `value_input` & `value`. Need to double check logic it doesn't trigger something twice, but other than that pretty exciting!

https://github.com/holoviz/panel/assets/15331990/ddcc6d3e-e53d-4523-94db-034dcdd972d6

- [ ] ensure text area is focused first
- [ ] docs
- [ ] tests

2024-02-23 06:42 UTC, ahuang11 commented on panel/chat/chatarea_input.py
> +        objects=["both", "width", "height", False],
default to height only.

2024-02-23 06:43 UTC, ahuang11 commented on panel/chat/chatarea_input.py
> +            self.value = self.value_input
```suggestion
        self.value = self.value_input
```

2024-02-23 08:30 UTC, philippjfr requested changes
My immediate feeling here is that we should reserve `ChatAreaInput` until we have a more complete and polished component with an inline send button rather than adding it simply for shift-Enter support. Also I don't think we should reset `value`/`value_input` on the Python side, I'd rather create a `ChatMessageEvent` that contains the value of the message and syncs the value with the `value` parameter on submit, while JS resets `value` and `value_input`.

2024-02-23 19:42 UTC, ahuang11 commented
Discussed with Philipp; we agreed that we can enhance ChatAreaInput over time since drop files is supported in text area (I think)
https://stackoverflow.com/questions/62093212/is-possible-drag-drop-files-into-standard-html-textarea

2024-02-25 15:22 UTC, philippjfr commented on panel/chat/__init__.py
> +from .chatarea_input import ChatAreaInput  # noqa
Would rename the module to `input.py`

2024-02-25 15:25 UTC, philippjfr commented on panel/chat/chatarea_input.py
> +        "value": None, **_PnTextAreaInput._rename,
If we want to be able to provide an initial message (which I'm not sure about), we'd have to add:

```python
def _get_properties(self, doc: Document) -> Dict[str, Any]:
    props = super()._get_properties(doc)
    props['value'] = self.value
    return props
```

2024-03-02 22:47 UTC, philippjfr approved these changes

2024-03-02 22:47 UTC, merged